exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once=gnome-keyring-daemon --start --components=secrets
exec-once=eval $(dbus-launch --sh-syntax)
exec-once=dbus-update-activation-environment --all
exec-once=wl-paste --type text --watch bash -c 'cliphist store && qs -c ii ipc call cliphistService update'
exec-once=wl-paste --type image --watch bash -c 'cliphist store && qs -c ii ipc call cliphistService update'
exec-once=easyeffects --hide-window --service-mode
exec-once=swayidle -w &
exec-once=qs -c ii
