monitor=,preferred,auto,1

general.gaps_in=4
general.gaps_out=5
general.gaps_workspace=50
general.border_size=1
general.active_border_color=rgba(0DB7D455)
general.inactive_border_color=rgba(31313600)
general.resize_on_border=true
general.allow_tearing=true

cursor.zoom_factor=1

input.kb_layout=us
input.numlock_by_default=true
input.repeat_delay=250
input.repeat_rate=35
input.follow_mouse=1
input.touchpad.natural_scroll=true
input.touchpad.disable_while_typing=true
input.touchpad.clickfinger_behavior=true
input.touchpad.scroll_factor=0.7

gesture.3.swipe=move
gesture.3.pinch=fullscreen
gesture.4.horizontal=workspace

decoration.rounding=18
decoration.rounding_power=2.5

dwindle.preserve_split=true
